const actionTypes = {
  GET_PUBLICCONFIG: 'GET_PUBLICCONFIG',
  GET_PUBLICCONFIG_SUCCESS: 'GET_PUBLICCONFIG_SUCCESS',
  GET_PUBLICCONFIG_FAILURE: 'GET_PUBLICCONFIG_FAILURE',
  SET_PUBLICCONFIG: 'SET_PUBLICCONFIG',
  SET_PUBLICCONFIG_SUCCESS: 'SET_PUBLICCONFIG_SUCCESS',
  SET_PUBLICCONFIG_FAILURE: 'SET_PUBLICCONFIG_FAILURE',
};

export default actionTypes;
